var buttonColours = ["red", "blue", "green", "yellow"];
var gamePattern = [];
var userClickedPattern = [];
var level = 0;
var started = false;


$(document).keypress(function() {
  if (!started) {
    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});



$(".btn").click(function() {

  var userChosenColour = this.id;
  userClickedPattern.push(userChosenColour);

  playSound(userChosenColour);
  animatePress(userChosenColour);
  checkAnswer((userClickedPattern.length - 1));

});

function nextSequence() {

  userClickedPattern = []; // once nextSequence is triggered, the userClickedPattern is set to an empty array

  level++; // increment level by 1
  $("#level-title").text("Level " + level); // modifies the title of the level

  var randomNumber = Math.round(Math.random() * 3);
  var randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);

  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomChosenColour);

}

function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function animatePress(currentColour) {
  $("#" + currentColour).addClass("pressed");
  setTimeout(function() {
    $("#" + currentColour).removeClass("pressed");
  }, 100);
}

function checkAnswer(currentLevel) { // take as input the index of the last answer

  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) { // check to see if the user's last answer is the same as the one generated by the game
    console.log("success");

    if (gamePattern.length === userClickedPattern.length) { // checks to user have finished their sequence
      setTimeout(function() { // call nextSequence after 1000 ms delay
        nextSequence();
      }, 1000);

    }
  } else {
    console.log("wrong");
    playSound("wrong");
    $("body").addClass("game-over");

    setTimeout(function() {
      $("body").removeClass("game-over");
    }, 200);

    $("#level-title").text("Game Over, Press Any Key to Restart");

    startOver(); // call start over if the user gets it wrong

  }

}

function startOver() {
  level = 0;
  gamePattern = [];
  userClickedPattern = [];
  started = false;
}
